=== AcaiPM/seeds/seed.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "https://raw.githubusercontent.com/AcaiPM/seeds/main/seed.schema.json",
    "title": "Acai Seed",
    "description": "Schema used for all Acai seeds.",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "homepage": {
            "type": "string"
        },
        "app_name": {
            "type": "string"
        },
        "app_version": {
            "type": "string"
        },
        "min_os": {
            "type": "string"
        },
        "file_type": {
            "type": "string"
        },
        "downloads": {
            "type": "object",
            "properties": {
                "arm64": {
                    "type": "string"
                },
                "amd64": {
                    "type": "string"
                }
            },
            "required": [
                "arm64",
                "amd64"
            ]
        },
        "uninstall": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "directories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "launchctl": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "other": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "files",
                "directories",
                "launchctl",
                "other"
            ]
        }
    },
    "required": [
        "name",
        "description",
        "homepage",
        "app_name",
        "app_version",
        "min_os",
        "file_type",
        "downloads",
        "uninstall"
    ]
}

=== AcaiPM/seeds/seeds/blockbench.json
{
    "name": "Blockbench",
    "description": "3D model editor for boxy models and pixel art textures",
    "homepage": "https://blockbench.net",
    "app_name": "Blockbench.app",
    "app_version": "4.7.4",
    "min_os": "10.13",
    "file_type": "dmg",
    "downloads": {
        "arm64": "https://github.com/JannisX11/blockbench/releases/download/v#{version}/Blockbench_arm64_#{version}.dmg",
        "amd64": "https://github.com/JannisX11/blockbench/releases/download/v#{version}/Blockbench_x64_#{version}.dmg"
    },
    "uninstall": {
        "files": [
            "~/Library/Preferences/blockbench.plist",
            "~/Library/Saved Application State/blockbench.savedState"
        ],
        "directories": [
            "~/Library/Application Support/Blockbench"
        ],
        "launchctl": [],
        "other": []
    }
}
